# Generated by Django 3.2.7 on 2024-03-13 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PVString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Azimuth', models.CharField(max_length=50, verbose_name='Azimuth')),
                ('Tilt', models.EmailField(max_length=254, verbose_name='Tilt')),
                ('Pnom', models.CharField(max_length=250, verbose_name='Pnominal')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PVString',
                'verbose_name_plural': 'PVStrings',
                'ordering': ('Username',),
            },
        ),
    ]
