# Generated by Django 3.2.7 on 2024-03-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvstring',
            name='Azimuth',
            field=models.FloatField(max_length=50, verbose_name='Azimuth'),
        ),
        migrations.AlterField(
            model_name='pvstring',
            name='Pnom',
            field=models.FloatField(max_length=250, verbose_name='Pnominal'),
        ),
        migrations.AlterField(
            model_name='pvstring',
            name='Tilt',
            field=models.FloatField(verbose_name='Tilt'),
        ),
    ]
