# Generated by Django 3.2.7 on 2024-03-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20240313_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvstring',
            name='PVCode',
            field=models.CharField(default='MA43-7C5', max_length=50, verbose_name='PVCode'),
            preserve_default=False,
        ),
    ]
