# Generated by Django 3.2.7 on 2024-03-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_pvstring_pvcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayIrradiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateNow', models.DateTimeField(verbose_name='DateNow')),
                ('IrrClass', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=5)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'DayIrradiance',
                'verbose_name_plural': 'DayIrradiances',
                'ordering': ('DateNow',),
            },
        ),
    ]
