# Generated by Django 3.2.7 on 2024-03-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_dayirradiance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayirradiance',
            name='DateNow',
            field=models.DateField(verbose_name='DateNow'),
        ),
    ]
